server:
  port: 8080
spring:
#  jpa:
#    show-sql: true
#    hibernate:
##    hbm2ddl-auto: validate

  jpa:
#    database-plateform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        use_sql_comments: true
        format_sql: true
        hbm2ddl.auto: update
      database-plateform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:~/agriTech;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    url: jdbc:h2:file:~/agriTech;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    plateform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    rest:
      base-path: /api
  thymeleaf:
    prefix: classpath:/templates
flyway:
  locations: db/migration/{vendor}
logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG

security:
  basic:
    enabled: true
    authorize-mode: NONE
#security.oauth2.client.client-id: agritech
#security.oauth2.client.client-secret: agritech
#security.oauth2.authorization.checkTokenAccess: isAuthenticated()
#security.oauth2.resource.filter-order: 3
#security:
#  oauth2:
#    resource:
#      id: agritech-client

---
spring:
  profiles: recette
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/agriTech
    username: root
    password: mypassword


